accounts/urls.py
from django.urls import path
from accounts import views

app_name='account'

urlpatterns = [ 
    path("login/", views.doLogin, name='user_login'),
    path("signup/", views.signup, name='signup'),
    path("logout/", views.logout_user, name='logout'),
    path("dashbord/", views.dashbord, name='dashbord'),
    path("my_orders/", views.my_orders, name='my_orders'),
    path("edit_profile/", views.edit_profile, name='edit_profile'),
    path("change_password/", views.change_password, name='change_password'),
    path("order_details/<int:order_id>/", views.order_details, name='order_details'),
    path("", views.dashbord, name='dashbord'),
    
    
    path("activate/<uidb64>/<token>/", views.activate, name='activate'),
    path('forgotPassword/',views.forgotPassword,name='forgotPassword'),
    path("confirm_password_validate/<uidb64>/<token>/", views.confirm_password_validate, name='confirm_password_validate'),
    path('resetPassword/',views.resetPassword,name='resetPassword'),
]

cart/urls.py
from django.urls import path
from cart import views

app_name ='cart'

urlpatterns = [

    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    
    path('cheakout/',views.cheakout,name='cheakout'),
    
]

greatkart/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', include('admin_honeypot.urls',namespace='admin_honeypot')),
    path('secure/', admin.site.urls),
    path('cart/',include('cart.urls')), 
    path('category/',include('category.urls')), 
    path('account/',include('accounts.urls')), 
    path('',include('store.urls')), 
    path('orders/',include('orders.urls')), 
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name ='store'

urlpatterns = [
    path('',views.index,name='home'),
    path('store/',views.store,name='store'),
    path('shop/',views.shop,name='shop'),
    path('shop/<slug:category_slug>/',views.shop,name='Products_by_category'),
    path('store/<slug:store_slug>/',views.store_page,name='store_page'),
    path('store/<slug:store_slug>/<slug:product_slug>/',views.product_detail,name='single_product'),
    path('search/',views.search,name='search'),
    path('submit_review/<int:product_id>/',views.submit_review,name='submit_review'),

]

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
    <div id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}
    </div>
    </div>
    {% endfor %}
{% endif %}

templates/includes/dashbord_sidebar.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/account/' == request.path %} active {% endif %}" href="{% url 'account:dashbord' %}"> Dashbord </a>
        <a class="list-group-item {% if '/account/my_orders/' == request.path %} active {% endif %}" href="{% url 'account:my_orders' %}"> My Orders </a>
        <a class="list-group-item {% if '/account/edit_profile/' == request.path %} active {% endif %}" href="{% url 'account:edit_profile'%}"> Edit Profile  </a>
        <a class="list-group-item {% if '/account/change_password/' == request.path %} active {% endif %}" href="{% url 'account:change_password' %}">Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'account:logout'%}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>

templates/includes/footer.html
{% load static %}

<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

<script>
	$(document).ready(function(){
		$(' .thumb a').click(function(e){
			e.preventDefault();
			$(' .mainImage img').attr('src',$(this).attr("href"));
		})
	})
</script>

</body>
</html>

templates/includes/header.html
{% load static %}


<header class="section-header">
    <section class="header-main border-bottom">
        <div class="container">
			<div class="row align-items-center">
				<div class="col-md-2 ">
					<a href="{% url 'store:home'%}" class="brand-wrap">
					<img class="logo" src="{% static './images/logo.png' %}">
					</a> <!-- brand-wrap.// -->
				</div>
				<div class="col-md-3 flex-grow-0">
					<div class="dropdown">
						<a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						  <i class="fa fa-bars" aria-hidden="true"></i> All Cagegory
						</a>
					  
						<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							{% for category in links %}
							<a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name}}</a> 
							{% endfor %}
						  
						  
						</div>
						<a href="{% url 'store:store' %}" class="btn btn-outline-primary mr-5">Store</a>
					</div>
				</div> <!-- col.// -->
	
				<div class="col-md-4 ">
					<form action="{% url 'store:search' %}" class="search" method="GET">
						<div class="input-group w-100 ">
							<input type="text" class="form-control" style="width:60%;" placeholder="Search" name="keyword">
							
							<div class="input-group-append">
							<button class="btn btn-primary" type="submit">
								<i class="fa fa-search"></i>
							</button>
							</div>
						</div>
					</form> <!-- search-wrap .end// -->
				</div> <!-- col.// -->
				<div class="col-md-3">
					<div class="d-flex justify-content-end mb-3 mb-lg-0">
						
						{% if user.id is None %}
						<div class="widget-header">
							<small class="title text-muted">Welcome Guest!</small>
							<div> 
								<a href="{% url 'account:user_login' %}">Sign in</a> <span class="dark-transp"> | </span>
								<a href="{% url 'account:signup' %}"> Register</a>
							</div>
						</div>
						{% else %}
						<div class="widget-header">
							<small class="title text-muted">Welcome {{ user.first_name }}!</small>
							<div> 
								<a href="{% url 'account:dashbord' %}">Dashbord</a> <span class="dark-transp"> | </span>
								<a href="{% url 'account:logout' %}"> Log Out</a>
							</div>
						</div>
						{% endif %}
							
						<a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3 ">
							<div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
							<span class="badge badge-pill badge-danger notify">{{cart_count}}</span>
						</a>
					</div> <!-- widgets-wrap.// -->
				</div> <!-- col.// -->
			</div> <!-- row.// -->
		</div> <!-- container.// -->
	</section> <!-- header-main .// -->
</header> <!-- section-header.// -->