accounts/urls.py
from django.urls import path
from accounts import views

app_name='account'

urlpatterns = [ 
    path("login/", views.doLogin, name='user_login'),
    path("signup/", views.signup, name='signup'),
    path("logout/", views.logout_user, name='logout'),
    path("dashbord/", views.dashbord, name='dashbord'),
    path("my_orders/", views.my_orders, name='my_orders'),
    path("edit_profile/", views.edit_profile, name='edit_profile'),
    path("change_password/", views.change_password, name='change_password'),
    path("order_details/<int:order_id>/", views.order_details, name='order_details'),
    path("", views.dashbord, name='dashbord'),
    
    
    path("activate/<uidb64>/<token>/", views.activate, name='activate'),
    path('forgotPassword/',views.forgotPassword,name='forgotPassword'),
    path("confirm_password_validate/<uidb64>/<token>/", views.confirm_password_validate, name='confirm_password_validate'),
    path('resetPassword/',views.resetPassword,name='resetPassword'),
]

cart/urls.py
from django.urls import path
from cart import views

app_name ='cart'

urlpatterns = [

    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/',views.remove_cart,name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/',views.remove_cart_item,name='remove_cart_item'),
    
    path('cheakout/',views.cheakout,name='cheakout'),
    
]

greatkart/urls.py
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', include('admin_honeypot.urls',namespace='admin_honeypot')),
    path('secure/', admin.site.urls),
    path('cart/',include('cart.urls')), 
    path('category/',include('category.urls')), 
    path('account/',include('accounts.urls')), 
    path('',include('store.urls')), 
    path('orders/',include('orders.urls')), 
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name ='store'

urlpatterns = [
    path('',views.index,name='home'),
    path('store/',views.store,name='store'),
    path('shop/',views.shop,name='shop'),
    path('shop/<slug:category_slug>/',views.shop,name='Products_by_category'),
    path('store/<slug:store_slug>/',views.store_page,name='store_page'),
    path('store/<slug:store_slug>/<slug:product_slug>/',views.product_detail,name='single_product'),
    path('search/',views.search,name='search'),
    path('submit_review/<int:product_id>/',views.submit_review,name='submit_review'),

]

store/models.py
from django.db import models
from django.urls import reverse
from category.models import Category
from django.conf import settings
from accounts.models import Account
from django.db.models import Avg,Count

class Store(models.Model):
    store_owner = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    store_name  = models.CharField(max_length=264,blank=True)
    store_slug  = models.SlugField(max_length=255,unique=True)
    store_image = models.ImageField(upload_to='store_profile_pic')
    created_at  = models.DateTimeField(auto_now_add=True)
    updated_at  = models.DateTimeField(auto_now=True)
    is_active   = models.BooleanField(default=True)
    
    def get_url(self):
        return reverse('store:store_page',args=[self.store_slug])
    
    def __str__(self):
        return self.store_name


class Product(models.Model):
    product_name   =models.CharField(max_length=255,unique=True)
    store          =models.ForeignKey(Store,on_delete=models.CASCADE)
    category       =models.ForeignKey(Category,on_delete=models.CASCADE)
    slug           =models.SlugField(max_length=255,unique=True)
    description    =models.TextField(max_length=500,blank=True)
    price          =models.IntegerField()
    old_price      =models.IntegerField()
    images         =models.ImageField( upload_to='products')
    stock          =models.IntegerField()
    is_available   =models.BooleanField(default=True)
    create_at      =models.DateTimeField( auto_now_add=True)
    update_at      =models.DateTimeField( auto_now=True)
    
    def get_url(self):
        return reverse('store:single_product',args=[self.store.store_slug, self.slug])
    
    def __str__(self):
        return self.product_name
    
    def averageReview(self):
        reviews=ReviewRating.objects.filter(product=self,status=True).aggregate(average=Avg('rating'))
        avg=0
        if reviews['average'] is not None:
            avg=float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews=ReviewRating.objects.filter(product=self,status=True).aggregate(count=Count('rating'))
        count=0
        if reviews['count'] is not None:
            count=int(reviews['count'])
        return count
            
 
class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager,self).filter(variation_category='color',is_active=True)
    
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size',is_active=True)
    
 
variation_category_choices=(
    ('color','color'),
    ('size','size'),  
)

class Variation(models.Model):
    product             = models.ForeignKey(Product,on_delete=models.CASCADE)
    variation_category  = models.CharField(max_length=100,choices=variation_category_choices)
    variation_value     =models.CharField(max_length=50)
    is_active           =models.BooleanField(default=True)
    create_at           =models.DateTimeField(auto_now_add=True)
    
    objects=VariationManager()
    
    def __str__(self):
        return self.variation_value
    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject
    
class ProductGallery(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    image=models.ImageField( upload_to='store/products', max_length=255)
    
    def __str__(self):
        return self.product.product_name
    
    class Meta:
        verbose_name = 'Product Gallery'
        verbose_name_plural = 'Product Gallery'
        
class HomeSlider(models.Model):
    images = models.ImageField(upload_to='homeslider')
    title = models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
    
    def __str__(self):
        return self.title
    
class StoreSlider(models.Model):
    images = models.ImageField(upload_to='storeslider')
    title = models.CharField(max_length=100)
    is_active=models.BooleanField(default=True)
    
    def __str__(self):
        return self.title

store/forms.py
from django import forms
from store.models import ReviewRating
class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = ReviewRating
        fields = ('subject','review','rating')

store/views.py
from django.db.models.query_utils import Q
from django.http.response import HttpResponse
from django.shortcuts import redirect, render,get_object_or_404
from cart.models import CartItem
from store.models import HomeSlider, ProductGallery, ReviewRating, Store,Product, StoreSlider
from accounts.models import UserProfile
from django.views.generic import DetailView
from category.models import Category
from cart.views import _cart_id
from django.core.paginator import Paginator
from django.db.models import Q
from store.forms import ReviewForm
from django.contrib import messages
from orders.models import OrderProduct


def index(request):
    product =Product.objects.all().filter(is_available=True)
    home_slider = HomeSlider.objects.filter(is_active=True)
    for prod in product:
         reviews=ReviewRating.objects.filter(product_id=prod.id,status=True)
    
    return render(request,'home.html',context={'product':product,'reviews':reviews,'home_slider':home_slider})

def shop(request,category_slug=None):
    categories =None
    product =None
    
    if category_slug != None:
        categories      = get_object_or_404(Category, slug=category_slug)
        product         = Product.objects.filter(category=categories, is_available=True)
        paginator=Paginator(product,1)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)
        product_count   =product.count()
    else:
        product =Product.objects.all().filter(is_available=True).order_by('id')
        paginator=Paginator(product,2)
        page=request.GET.get('page')
        paged_products=paginator.get_page(page)
        product_count=product.count()
    return render(request,'shop.html',context={'product':paged_products,'product_count':product_count})

def store(request):
    store=Store.objects.all().filter(is_active=True)
    store_slider =StoreSlider.objects.filter(is_active=True)
    return render(request,'store.html',context={'store':store,'store_slider':store_slider})

def store_page(request,store_slug):
    store_page =Store.objects.get(store_slug=store_slug)
    product=Product.objects.filter(store=store_page)
    return render(request,'store_page.html',context={'store_page':store_page,'product':product})

def product_detail(request,store_slug,product_slug):
    try:
        single_product =Product.objects.get(store__store_slug=store_slug,slug=product_slug)
        in_cart =CartItem.objects.filter(cart__cart_id=_cart_id(request),product=single_product).exists()
    except Exception as e:
        raise e
    if request.user.is_authenticated:
        try:
            orderproduct=OrderProduct.objects.filter(user=request.user,product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct=None
    else:
        orderproduct=None
      
    reviews=ReviewRating.objects.filter(product_id=single_product.id,status=True)
    
    
    product_gallery=ProductGallery.objects.filter(product_id = single_product.id)
    
    return render(request,'product_detail.html',context={'single_product':single_product,'in_cart':in_cart,'orderproduct':orderproduct,'reviews':reviews,'product_gallery':product_gallery})

def search(request):
    if 'keyword' in request.GET:
        keyword=request.GET['keyword']
        if keyword:
            product =Product.objects.order_by('-create_at').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count=product.count()
        
    return render(request,'shop.html',context={'product':product,'product_count':product_count})


def submit_review(request,product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method =='POST':
        try:
            reviews=ReviewRating.objects.get(user__id=request.user.id,product__id=product_id)
            form=ReviewForm(request.POST,instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data=ReviewRating()
                data.subject=form.cleaned_data['subject']
                data.review=form.cleaned_data['review']
                data.rating=form.cleaned_data['rating']
                data.ip=request.META.get('REMOTE_ADDR')
                data.product_id=product_id
                data.user_id=request.user.id
                data.save()
                messages.success(request, 'Thank you! Your review has been Submitted.')
                return redirect(url)
                
      

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="cache-control" content="max-age=604800" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>{% block title %} {% endblock title %}</title>
        
        <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
        
        <!-- jQuery -->
        
        
        <!-- Bootstrap4 files-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
        
        
        <!-- Font awesome 5 -->
        <link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">
        
        <!-- custom style -->
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- custom javascript -->
        <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
        <script src="https://www.paypal.com/sdk/js?client-id=ASxgYvqPfy0XnN9LmxDDPzJEg4DIDUSmlTYzhiSdS9iZ2WrWILMkFLoalbXtvVOxiVhDw_j4qCHgz3RX&currency=USD"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
        


		{% block css %}
		{% endblock css %}

        
        <script type="text/javascript">
        /// some script
        
        // jquery ready start
        $(document).ready(function() {
            // jQuery code
        
        });
        // jquery end
        </script>
        
        </head>
<body>

<!-- ========================= HEADER ========================= -->
{% block header %}
  
{% endblock header %}
<!-- ========================= HEADER END // ========================= -->


<!-- ========================= SECTION CONTENT ========================= -->
{% block content %}
  
{% endblock content %}
<!-- ========================= SECTION  END// ========================= -->


<!-- ========================= FOOTER ========================= -->
{% block footer %}
  
{% endblock footer %}
<!-- ========================= FOOTER END // ========================= -->
{% block js %}
    
{% endblock js %}
</body>
</html>

templates/content.html
{% load static %}

<section class="section-intro padding-y-sm">
	<div class="container">
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
		  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner">
			{% for i in home_slider %}
			<div class="carousel-item {% if forloop.first %} active {% else %} {% endif %}">
				<img src="{{ i.images.url }}" class="d-block w-100" height="300px" width="1200px" alt="...">
			</div>
		  {% endfor %}
		</div>
		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  <span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  <span class="sr-only">Next</span>
		</a>
	  </div>
	</div>
</section>
<!-- ========================= SECTION MAIN END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name padding-y-sm">
    <div class="container">
        <header class="section-heading">
                <div class="row">
                <div class="col-md-6">
                    <h3 class="section-title">Popular products</h3>
                </div>
                <div class="col-md-6 ">
                    <a href="{% url 'store:shop' %} "class="btn btn-outline-primary ">See all</a>
                </div>
                </div>
                
        </header><!-- sect-heading -->

        
        <div class="row">
            {% for product in product %}

            <div class="col-md-3">
                <div class="card card-product-grid">
                    <a href="{{ product.get_url }}" class="img-wrap"> <img src="media/{{ product.images}}"> </a>
                    <figcaption class="info-wrap">
                        <a href="{{ product.get_url }}" class="title">{{ product.product_name}}</a>
						<small><a href="{{ product.store.get_url }} ">{{ product.store.store_name}}</small></a>
                        <div class="price mt-1">${{product.price}}</div> <!-- price-wrap.// -->
						<div class="rating-star">
							<span>
								<i class="fa fa-star{% if product.averageReview < 0.5 %}-o{% elif product.averageReview >= 0.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 1.5 %}-o{% elif product.averageReview >= 1.5 and product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 2.5 %}-o{% elif product.averageReview >= 2.5 and product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 3.5 %}-o{% elif product.averageReview >= 3.5 and product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
								<i class="fa fa-star{% if product.averageReview < 4.5 %}-o{% elif product.averageReview >= 4.5 and product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
							</span>
						</div>
                    </figcaption>
                </div>
            </div> <!-- col.// -->
            
            {% endfor %}
        </div> <!-- row.// -->

    </div><!-- container // -->
</section>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {% endblock title %}

{% block css %}
{% endblock css %}
{% block header %}
{% include "includes/header.html" %}
{% endblock header %}


{% block content %}
{% include "content.html" %} 
{% endblock content %}





{% block footer %}
{% include "includes/footer.html" %}
{% endblock footer %}
{% block js %}
    
{% endblock js %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{single_product.product_name}} {% endblock title %}

{% block css %}
{% endblock css %}
{% block header %}
{% include "includes/header.html" %}
{% endblock header %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap"> 
                    <div class="img-big-wrap mainImage">
                    <center> <img src="/media/{{ single_product.images}}"> </center>
                    </div> <!-- img-big-wrap.// -->
                </article> <!-- gallery-wrap .end// -->
                <ul class="thumb">
                    <li>
                        <a href="/media/{{ single_product.images}}" target="mainImage"> <img src="/media/{{ single_product.images}}" alt="Product Image"> </a>
                        {% for i in product_gallery %}
                        <a href="{{ i.image.url }}" target="mainImage"> <img src="{{ i.image.url }}" alt="Product Image"> </a> 
                        {% endfor %}
                    </li>
                </ul>

            </aside>
            <main class="col-md-6 border-left">
    <form action="{% url 'cart:add_cart' single_product.id %}" method="POST">
        {% csrf_token %}
        <article class="content-body">
        <h2 class="title">{{single_product.product_name}}</h2>
        <div class="mb-3"> 
            <div class="rating-star">
                <span>
                    <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                    <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                </span>
                <span>{{ single_product.averageReview }}</span> <br>
                <span>{{ single_product.countReview }} </span> Reviews


            </div>
             <br>
            <var class="price h4">${{single_product.price}}</var> 
        </div> 
        {{ single_product.description}}
        <hr>
            <div class="row">
                <div class="item-option-select">
                  <h6>Choose Color</h6>
                    <select name="color" id="" class="form-control" required>
                        <option value="" desable selected>Choose Color</option>
                        {% for i in single_product.variation_set.colors %}
                        <option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst }}</option> 
                        {% endfor %}
                    </select>
                </div>
            </div> <!-- row.// -->
            <div class="row">
                <div class="item-option-select">
                  <h6>Choose Size</h6>
                  <select name="size" id="" class="form-control">
                    <option value="" desable selected>Choose Size</option>
                        {% for i in single_product.variation_set.sizes %}
                        <option value="{{ i.variation_value | lower}}">{{ i.variation_value | capfirst }}</option> 
                        {% endfor %}
                  </select>
                </div>
            </div> <!-- row.// -->
            <hr>
            {% if single_product.stock <= 0 %}
            <button type="button" class="btn btn-block btn-danger" disabled>Out of Stock</button>
            {% else %} 
             
              <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
              
            {% endif %}
        </article> <!-- product-info-aside .// -->
    </form>
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    <form action="{% url 'store:submit_review' single_product.id %}" method="POST">
        {% include 'includes/alerts.html' %}
        {% csrf_token %}
        <h5>Write Your Review</h5>
        <div>
            <!-- Rating stars -->
			<label>How do you rate this product?</label>
			<br>
            <div class="rate">
                <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
                <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
                <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
                <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
                <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
                <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
                <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
                <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
                <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
                <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
            </div>
            <br>
            Review Title:
            <input type="text" class="form-control" name="subject">
            <br>
            Review:
            <textarea name="review" rows="4" class="form-control"></textarea>
            <br>
            {% if user.is_authenticated %}
               {% if orderproduct %}
                    <input type="submit" value="Submit Review" class="btn btn-primary">
               {% else %}
               <p>You must purchase this product for post a review. </p>    
               {% endif %}
                   
                    
            {% else %}						
            <p>You must be logged in to post a review. <span><a href="{% url 'account:user_login' %}">Login now</a></span></p>
            {% endif %}
        </div>
        
    </form>
    
    
    <div class="row">
        <div class="col-md-9">
            <header class="section-heading">
                <h3>Customer Reviews </h3>  
            </header>
            {% for review in reviews %}
                <article class="box mb-3">
                    <div class="icontext w-100">
                        
                          <img src="{% static 'images/avatars/avatar2.png'%}" alt="User Profile Picture" class="img-xs icon rounded-circle">
                         
                        <div class="text">
                            <span class="date text-muted float-md-right">{{ review.updated_at }}</span>  
                            <h6 class="mb-1">{{ review.user.full_name }}</h6>
                            
                        </div>
                    </div> <!-- icontext.// -->
                    <div class="mt-3">
                        <div class="rating-star">
                            <span>
                                <i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                                <i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                            </span>
                        </div>
                        <h6>{{ review.subject }}</h6>
                        <p>
                           {{ review.review }}
                        </p>	
                    </div>
                </article>
            {% endfor %}
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
     

{% endblock content %}


{% block footer %}
{% include "includes/footer.html" %}
{% endblock footer %}
{% block js %}
    
{% endblock js %}